steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['sql', 'instances', 'create', '$INSTANCE_NAME', '--project=$PROJECT_ID', '--database-version=MYSQL_5_7', '--tier=db-n1-standard-1', '--region=us-central1']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-app', '--image', 'gcr.io/$PROJECT_ID/my-app', '--add-cloudsql-instances', '$INSTANCE_CONNECTION_NAME', '--update-env-vars', 'INSTANCE_CONNECTION_NAME=$INSTANCE_CONNECTION_NAME', '--region', 'us-central1', '--platform', 'managed']